# Generated by Django 5.2.4 on 2025-08-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='memo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', '未完了'), ('done', '完了')], default='pending', max_length=10),
        ),
    ]
